language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests and deploy project
script:
  - python -m pytest
  - python3 -m pip install --upgrade setuptools wheel twine
  - python3 setup.py sdist bdist_wheel
  - python3 -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*

# для email уведомлений при любом результате сборки
notifications:
  email:
    on_success: always
    on_failure: always
